# Generated by Django 4.2.16 on 2024-10-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='upload/')),
                ('note', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('chosestatus', models.CharField(choices=[('great', 'Great'), ('not_great', 'Not Great')], default='not_great', max_length=10)),
            ],
        ),
    ]
